import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import { getServerSession } from 'next-auth'
import { authOptions } from '../pages/api/auth/[...nextauth]'
import LogoutBtn from '../app/components/LogoutBtn'
import LoginBtn from '../app/components/LoginBtn'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  //로그인된 유저정보 출력
  // 서버컴포넌트, 서버기능안에서 사용가능
  let session: any = await getServerSession(authOptions);
  
  return (
    <html lang="ko">
      <body className={inter.className}>
        <div className="bg-white p-21"> 
          <Link href="/" className="mr-10px decoration-none text-black font-bold p-5">Appleforum</Link> 
          <Link href="/list" className="mr-10px decoration-none text-black p-5">List</Link> 
          {
            session 
            ? 
            <span>{session.user.name} <LogoutBtn /></span> 
            : 
            <LoginBtn />
          }
          
        </div>  
        {children}
      </body>
    </html>
  )
}
