import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import LoginBtn from '@/components/LoginBtn'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import LogoutBtn from '@/components/LogoutBtn'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  //로그인된 유저정보 출력
  // 서버컴포넌트, 서버기능안에서 사용가능
  let session = await getServerSession(authOptions);
  console.log(session)
  
  return (
    <html lang="ko">
      <body className={inter.className}>
        <div className="navbar"> 
          <Link href="/" className="logo">Appleforum</Link> 
          <Link href="/list">List</Link> 
          {
            session 
            ? 
            <span>{session.user.name} <LogoutBtn /></span> 
            : 
            <LoginBtn />
          }
          
        </div>  
        {children}
      </body>
    </html>
  )
}
