import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import { getServerSession } from 'next-auth'
import { authOptions } from '../pages/api/auth/[...nextauth]'
import LogoutBtn from '../app/components/LogoutBtn'
import LoginBtn from '../app/components/LoginBtn'
import RegisterBtn from './components/RegisterBtn'
import RecoilRootProvider from './components/RecoilRootProvider'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  //로그인된 유저정보 출력
  // 서버컴포넌트, 서버기능안에서 사용가능
  let session: any = await getServerSession(authOptions);
  
  return (
    <html lang="ko">
      <body className={inter.className}>
        <div className="bg-white p-21"> 
          <Link href="/" className="decoration-none text-black font-bold p-5">Appleforum</Link> 
          <Link href="/list" className="decoration-none text-black p-5">List</Link> 
          {
            session 
            ? 
            <span>
              <Link href="/write" className="decoration-none text-black p-5">글쓰기</Link> 
              <Link href="/chat" className="decoration-none text-black p-5">채팅</Link> 
              [<span className='font-bold'>{session.user.name}</span>]님 안녕하세요<LogoutBtn />
            </span> 
            : 
            <span>
              <LoginBtn />
              <RegisterBtn />
            </span>
          }
          
        </div>  
        <RecoilRootProvider>{children}</RecoilRootProvider>
      </body>
    </html>
  )
}
